const lessonData = {};

lessonData["01_Ajax.mp3"] = [{
    text: "Operation Ajax was a secret mission planned by the intelligence agencies of the United States and the United Kingdom. In 1953, the leader of Iran, Mohammad Mossadegh, decided to take control of the country's oil. Before this, British companies controlled the oil and made a lot of money. The British were very angry and asked the Americans for help. The CIA and the British secret service started a plan to remove Mossadegh from power. They spent a lot of money to pay people to protest in the streets and cause trouble. They also talked to the Iranian military and the Shah, who was the King of Iran. After a few days of chaos and fighting, the military arrested Mossadegh. The Shah returned to power and became a very strong leader with the help of the West. This operation was a success for the US and UK, but it made many Iranians very angry. They felt that other countries were interfering in their business. This event changed the history of the Middle East forever and led to many political problems in the future.",
    dict: { "secret": "gizli", "mission": "görev", "planned": "planlandı", "intelligence": "istihbarat", "agencies": "ajanslar/teşkilatlar", "decided": "karar verdi", "control": "kontrol", "oil": "petrol", "companies": "şirketler", "made": "yaptı/kazandı", "angry": "kızgın/öfkeli", "remove": "kaldırmak/uzaklaştırmak", "power": "güç/iktidar", "spent": "harcadılar", "pay": "ödemek", "protest": "protesto etmek", "streets": "sokaklar", "cause": "sebep olmak", "trouble": "sorun/bela", "military": "askeri/ordu", "chaos": "kaos/kargaşa", "fighting": "çatışma/kavga", "arrested": "tutukladı", "returned": "geri döndü", "strong": "güçlü", "success": "başarı", "interfering": "müdahale eden", "business": "iş", "changed": "değiştirdi", "history": "tarih", "forever": "sonsuza dek", "led": "yol açtı", "political": "siyasi", "problems": "sorunlar", "future": "gelecek" },
    questions: [ {q:"Was Operation Ajax a secret mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Mossadegh decide to take control of the oil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they spend no money to pay people to protest?", a_en:"No", a_tr:"Hayır"}, {q:"Did the military arrest Mossadegh?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Shah return to power?", a_en:"Yes", a_tr:"Evet"}, {q:"Did this operation make Iranians very happy?", a_en:"No", a_tr:"Hayır"}, {q:"Did this event change the history of the Middle East?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_Anthropoid.mp3"] = [{
    text: "Operation Anthropoid was a very dangerous and daring mission during World War II. The goal was to assassinate Reinhard Heydrich. He was a very powerful Nazi leader and was known as the 'Butcher of Prague' because he was very cruel. Two brave soldiers, Jozef Gabčík and Jan Kubiš, were trained in England and then jumped from a plane into Czechoslovakia at night. They lived in hiding for many months while they planned the attack. In May 1942, they waited for Heydrich’s car on a sharp corner in the city. When the car slowed down, they tried to shoot him, but their gun jammed. Then, they threw a bomb at the car. Heydrich was badly injured and died a few days later in the hospital. The Nazi soldiers were very angry and searched everywhere for the two men. Finally, the soldiers found them in a church. After a long and heroic gunfight, the two brave men died. This mission showed the world that the Nazis were not invincible, but it also led to terrible revenge against the local people.",
    dict: { "dangerous": "tehlikeli", "daring": "cesur", "mission": "görev", "goal": "hedef", "assassinate": "suikast düzenlemek", "powerful": "güçlü", "known": "bilinen", "Butcher": "Kasap", "cruel": "zalim", "brave": "cesur", "soldiers": "askerler", "trained": "eğitildi", "jumped": "atladılar", "plane": "uçak", "hiding": "saklanma", "planned": "planladılar", "attack": "saldırı", "waited": "beklediler", "sharp": "keskin", "corner": "köşe", "slowed down": "yavaşladı", "shoot": "ateş etmek", "gun": "silah", "jammed": "tutukluk yaptı", "threw": "attılar", "bomb": "bomba", "badly": "kötü bir şekilde", "injured": "yaralandı", "died": "öldü", "hospital": "hastane", "searched": "aradılar", "everywhere": "her yer", "church": "kilise", "heroic": "kahramanca", "gunfight": "silahlı çatışma", "showed": "gösterdi", "invincible": "yenilmez", "terrible": "korkunç", "revenge": "intikam", "against": "karşı", "local": "yerel" },
    questions: [ {q:"Was the goal to assassinate Reinhard Heydrich?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the two soldiers trained in England?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they jump from a plane at night?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their gun work perfectly?", a_en:"No", a_tr:"Hayır"}, {q:"Did they throw a bomb at the car?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the Nazis invincible?", a_en:"No", a_tr:"Hayır"}, {q:"Did this mission lead to terrible revenge?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_Argo.mp3"] = [{
    text: "Operation Argo is one of the most famous and clever rescue missions in history. In 1979, during the Iran Hostage Crisis, protesters took over the American Embassy in Tehran. Most people were taken hostage, but six Americans managed to escape and hide in the home of the Canadian ambassador. They were trapped and very afraid of being caught. A CIA agent named Tony Mendez created a brilliant plan to save them. He pretended that the six Americans were a film crew from Canada. He said they were in Iran to find a location for a new science-fiction movie called Argo. He even created fake movie posters and advertisements in magazines. Mendez flew to Tehran with fake passports and met the group. He taught them how to act like movie makers. At the airport, they showed their fake documents to the guards. The plan worked perfectly, and they flew out of Iran safely. The world knew nothing about the truth for many years until it was finally made into a famous movie.",
    dict: { "famous": "ünlü", "clever": "zeki/akıllı", "rescue": "kurtarma", "missions": "görevler", "protesters": "protestocular", "took over": "ele geçirdi", "Embassy": "Büyükelçilik", "hostage": "rehine", "managed": "başardılar", "escape": "kaçmak", "hide": "saklanmak", "ambassador": "büyükelçi", "trapped": "kapana kısılmış", "afraid": "korkmuş", "caught": "yakalanmış", "agent": "ajan", "brilliant": "parlak/muhteşem", "plan": "plan", "save": "kurtarmak", "pretended": "numara yaptı", "film crew": "film ekibi", "location": "mekan/yer", "science-fiction": "bilim kurgu", "fake": "sahte", "posters": "afişler", "advertisements": "reklamlar", "magazines": "dergiler", "passports": "pasaportlar", "met": "buluştu", "taught": "öğretti", "act": "davranmak", "airport": "havalimanı", "documents": "belgeler", "guards": "korumalar", "worked": "işe yaradı", "perfectly": "mükemmel şekilde", "safely": "güvenle", "nothing": "hiçbir şey", "truth": "gerçek" },
    questions: [ {q:"Was it a clever rescue mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did protesters take over the American Embassy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did six Americans manage to escape?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the CIA agent pretend they were doctors?", a_en:"No", a_tr:"Hayır"}, {q:"Did he create fake movie posters?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the plan fail at the airport?", a_en:"No", a_tr:"Hayır"}, {q:"Did the world know nothing about the truth for many years?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_BayOfPigs.mp3"] = [{
    text: "The Bay of Pigs Invasion was a major secret operation that became a very famous failure. In 1961, the United States government wanted to remove the Cuban leader, Fidel Castro, from power. The CIA trained a group of Cuban exiles to become a secret army. The plan was for this army to land on a beach called the Bay of Pigs and start a revolution against Castro. The US thought that the local Cuban people would help the rebels. However, everything went wrong. When the group landed on the beach, the Cuban military was already waiting for them. The US provided no air support, so the rebels were quickly defeated or captured. Fidel Castro became even more popular in Cuba after this victory. The operation was a big embarrassment for President John F. Kennedy and the United States. It made the relationship between the US and Cuba very bad for a long time and pushed Cuba to become closer friends with the Soviet Union.",
    dict: { "Invasion": "İşgal", "major": "büyük/önemli", "secret": "gizli", "operation": "operasyon", "failure": "başarısızlık", "government": "hükümet", "remove": "uzaklaştırmak/kaldırmak", "power": "güç/iktidar", "trained": "eğitti", "exiles": "sürgünler", "army": "ordu", "land": "karaya çıkmak", "beach": "plaj/kumsal", "revolution": "devrim", "against": "karşı", "thought": "düşündü", "local": "yerel", "rebels": "isyancılar", "wrong": "yanlış", "military": "ordu/askeri", "waiting": "bekleyen", "provided": "sağladı", "air support": "hava desteği", "quickly": "hızlıca", "defeated": "yenildi", "captured": "yakalandı", "popular": "popüler", "victory": "zafer", "embarrassment": "utanç", "relationship": "ilişki", "between": "arasında", "pushed": "itti", "closer": "daha yakın" },
    questions: [ {q:"Was the Bay of Pigs a famous failure?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the US want to remove Fidel Castro from power?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the CIA train a group of Cuban exiles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the US provide massive air support?", a_en:"No", a_tr:"Hayır"}, {q:"Were the rebels quickly defeated?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Fidel Castro become more popular after this?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the operation a big success for President Kennedy?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["05_Brothers.mp3"] = [{
    text: "Operation Brothers was a spectacular secret mission by Mossad, the Israeli intelligence agency. Thousands of Jewish refugees from Ethiopia were stuck in dangerous camps in Sudan. Israel wanted to save them and bring them home. Mossad agents found an empty, abandoned holiday resort on the coast of the Red Sea in Sudan. They pretended to be a European travel company and opened the 'Arous on the Sea' diving resort. They even hired local workers and hosted real tourists who had no idea the staff were secret agents. At night, when the tourists were sleeping, the agents drove to the refugee camps. they picked up groups of people and brought them to the beach. From there, the refugees were put onto small boats and then onto large Israeli ships or planes. For several years, they secretly moved thousands of people while running a successful hotel during the day. This daring operation saved many lives and stayed a secret until the agents finally had to escape when the Sudanese government became suspicious.",
    dict: { "spectacular": "muhteşem", "intelligence": "istihbarat", "agency": "ajans/teşkilat", "refugees": "mülteciler", "stuck": "sıkışmış/mahsur kalmış", "dangerous": "tehlikeli", "camps": "kamplar", "save": "kurtarmak", "bring": "getirmek", "empty": "boş", "abandoned": "terk edilmiş", "resort": "tatil köyü", "coast": "sahil/kıyı", "pretended": "numara yaptılar", "travel": "seyahat", "diving": "dalış", "hired": "işe aldılar", "local": "yerel", "workers": "işçiler", "hosted": "ağırladılar", "tourists": "turistler", "idea": "fikir", "staff": "personel", "sleeping": "uyuyan", "drove": "sürdüler", "picked up": "aldılar/topladılar", "beach": "plaj", "boats": "tekneler/botlar", "ships": "gemiler", "planes": "uçaklar", "secretly": "gizlice", "moved": "taşıdılar", "running": "işleten", "successful": "başarılı", "daring": "cesur", "lives": "hayatlar", "stayed": "kaldı", "escape": "kaçmak", "suspicious": "şüpheli" },
    questions: [ {q:"Was Operation Brothers a mission by Mossad?", a_en:"Yes", a_tr:"Evet"}, {q:"Were Jewish refugees stuck in dangerous camps?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the agents open a diving resort?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the real tourists have no idea about the secret agents?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they move the refugees during the daytime?", a_en:"No", a_tr:"Hayır"}, {q:"Did they secretly move thousands of people?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the agents stay in Sudan forever?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["06_CarlosTheJackal.mp3"] = [{
    text: "Carlos the Jackal was once the most wanted terrorist in the whole world. His real name was Ilich Ramírez Sánchez. He was responsible for many bombings and kidnappings across Europe for many years. For a long time, nobody could find him because he was very good at hiding. In 1994, French intelligence discovered that he was living in Khartoum, the capital city of Sudan. He was there to have a small medical operation. The French government made a secret deal with the Sudanese government to capture him. One night, while Carlos was recovering from his surgery, Sudanese agents went to his room. They told him they were moving him for his safety, but then they drugged him so he would fall asleep. They handed him over to French agents who were waiting with a private plane. When Carlos woke up, he was in a prison in France. He was very surprised because he thought he was safe in Sudan. He was put on trial and sent to prison for life. This was a major victory for international justice.",
    dict: { "wanted": "aranan", "terrorist": "terörist", "whole": "bütün", "real": "gerçek", "responsible": "sorumlu", "bombings": "bombalamalar", "kidnappings": "adam kaçırmalar", "nobody": "hiç kimse", "find": "bulmak", "hiding": "saklanma", "discovered": "keşfetti", "capital": "başkent", "medical": "tıbbi", "operation": "ameliyat/operasyon", "secret": "gizli", "deal": "anlaşma", "capture": "yakalamak", "recovering": "iyileşen", "surgery": "ameliyat", "agents": "ajanlar", "safety": "güvenlik", "drugged": "ilaç verdiler (uyuşturmak)", "fall asleep": "uykuya dalmak", "handed over": "teslim ettiler", "waiting": "bekleyen", "private": "özel", "plane": "uçak", "woke up": "uyandı", "prison": "hapishane", "surprised": "şaşırmış", "thought": "düşündü", "safe": "güvenli", "trial": "duruşma", "life": "hayat/ömür boyu", "victory": "zafer", "international": "uluslararası", "justice": "adalet" },
    questions: [ {q:"Was Carlos the Jackal a wanted terrorist?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he responsible for bombings and kidnappings?", a_en:"Yes", a_tr:"Evet"}, {q:"Could nobody find him for a long time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the French government make a deal with Sudan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the agents shoot him with a gun?", a_en:"No", a_tr:"Hayır"}, {q:"Did they hand him over to French agents?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he sent to prison for life?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_Diamond.mp3"] = [{
    text: "In the 1960s, the Soviet Union had a new, top-secret fighter jet called the MiG-21. It was very fast and dangerous, and the West wanted to know its secrets. Mossad, the Israeli secret service, started Operation Diamond to steal one. They spent years looking for an Arab pilot who was willing to help them. Finally, they found an Iraqi pilot named Munir Redfa. He was unhappy with his life in Iraq and agreed to fly the jet to Israel. Mossad promised him a large amount of money and promised to move his entire family to a safe place. In August 1966, during a training flight, Redfa suddenly changed his direction and flew toward Israel. Iraqi jets tried to follow him, but he was too fast. He landed the MiG-21 in Israel, and the world was shocked. Israeli and American scientists studied the jet to learn how to defeat it in battle. This mission gave Israel a huge advantage in the air and Redfa lived the rest of his life in safety under a new name.",
    dict: { "top-secret": "çok gizli", "fighter jet": "savaş uçağı", "called": "adlandırılan", "fast": "hızlı", "dangerous": "tehlikeli", "secrets": "sırlar", "steal": "çalmak", "spent": "harcadılar", "looking for": "arayarak", "pilot": "pilot", "willing": "istekli", "unhappy": "mutsuz", "agreed": "kabul etti", "fly": "uçurmak", "promised": "söz verdi", "amount": "miktar", "money": "para", "entire": "bütün/tüm", "family": "aile", "safe": "güvenli", "place": "yer", "during": "sırasında", "training": "eğitim", "flight": "uçuş", "suddenly": "aniden", "changed": "değiştirdi", "direction": "yön", "toward": "doğru", "tried": "denedi", "follow": "takip etmek", "landed": "indirdi", "shocked": "şok olmuş", "scientists": "bilim insanları", "studied": "inceledi/çalıştı", "defeat": "yenmek", "battle": "savaş", "huge": "büyük", "advantage": "avantaj", "air": "hava", "rest": "geri kalan" },
    questions: [ {q:"Did the Soviet Union have a new fighter jet?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Mossad start Operation Diamond to steal it?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they find an Iraqi pilot willing to help?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Mossad promise him no money?", a_en:"No", a_tr:"Hayır"}, {q:"Did Iraqi jets manage to catch him?", a_en:"No", a_tr:"Hayır"}, {q:"Did scientists study the jet to learn its secrets?", a_en:"Yes", a_tr:"Evet"}, {q:"Did this mission give Israel a huge advantage?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_EagleClaw.mp3"] = [{
    text: "Operation Eagle Claw was a high-stakes rescue mission that ended in a tragic blunder. In 1980, 52 Americans were being held hostage in the US Embassy in Tehran. President Jimmy Carter ordered a secret mission to save them. The plan was very complicated and involved many helicopters and planes landing in a remote part of the Iranian desert called 'Desert One.' From there, soldiers would drive to Tehran to rescue the hostages. However, a massive sandstorm hit the area and damaged several helicopters. The mission was already very difficult, and the commander decided to cancel it. As the aircraft were trying to leave the desert in the dark, a helicopter crashed into a transport plane. The crash caused a massive fire and eight American soldiers died. The rest of the team had to leave quickly, leaving behind equipment and the bodies of their friends. This failure was a huge disaster for the US government and it showed how difficult secret rescue missions can be in dangerous environments.",
    dict: { "high-stakes": "yüksek riskli", "rescue": "kurtarma", "mission": "görev", "ended": "bitti", "tragic": "trajik", "blunder": "büyük hata/gaf", "held": "tutulan", "hostage": "rehine", "Embassy": "Büyükelçilik", "ordered": "emretti", "save": "kurtarmak", "complicated": "karmaşık", "involved": "içeriyordu", "helicopters": "helikopterler", "landing": "iniş", "remote": "uzak/ıssız", "desert": "çöl", "drive": "sürmek", "massive": "muazzam", "sandstorm": "kum fırtınası", "hit": "vurdu", "damaged": "hasar verdi", "several": "birkaç", "difficult": "zor", "commander": "komutan", "decided": "karar verdi", "cancel": "iptal etmek", "aircraft": "uçak/hava aracı", "leave": "ayrılmak", "dark": "karanlık", "crashed": "çarptı", "transport": "nakliye", "caused": "sebep oldu", "fire": "yangın", "died": "öldü", "rest": "geri kalan", "quickly": "hızlıca", "leaving behind": "geride bırakarak", "equipment": "ekipman", "bodies": "cesetler/bedenler", "failure": "başarısızlık", "disaster": "felaket", "environments": "ortamlar" },
    questions: [ {q:"Was Operation Eagle Claw a high-stakes rescue mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Were 52 Americans held hostage in Tehran?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the plan very simple and easy?", a_en:"No", a_tr:"Hayır"}, {q:"Did a massive sandstorm hit the area?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the commander decide to cancel the mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a helicopter crash into a transport plane?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the operation a massive success?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["09_Entebbe.mp3"] = [{
    text: "Operation Entebbe is one of the most successful and spectacular rescue missions ever. In 1976, four hijackers took control of an Air France plane and forced it to land in Entebbe, Uganda. They released most of the passengers but kept more than 100 Jewish and Israeli people as hostages. They threatened to kill them if their demands met no success. The Ugandan leader, Idi Amin, was actually helping the hijackers. Israel decided to launch a secret rescue mission. They flew four giant transport planes thousands of miles at night, flying very low to avoid radar. When they landed at the airport, the commandos rushed out in a black Mercedes car that looked like Idi Amin's car to confuse the guards. They attacked the airport building, killed the hijackers, and rescued the hostages in just 90 minutes. Only one Israeli soldier, Yonatan Netanyahu, was killed during the fight. The mission shocked the world and showed that Israel could protect its citizens anywhere on Earth.",
    dict: { "successful": "başarılı", "spectacular": "muhteşem", "hijackers": "korsanlar", "took control": "kontrolü ele aldı", "forced": "zorladı", "land": "inmek", "released": "serbest bıraktı", "passengers": "yolcular", "kept": "tuttu", "hostages": "rehineler", "threatened": "tehdit etti", "kill": "öldürmek", "demands": "talepler", "success": "başarı", "actually": "aslında", "helping": "yardım eden", "launch": "başlatmak", "flew": "uçurdu", "giant": "dev", "transport": "nakliye", "miles": "miller", "night": "gece", "low": "alçak", "avoid": "kaçınmak", "radar": "radar", "commandos": "komandolar", "rushed out": "dışarı fırladılar", "looked like": "gibi görünüyordu", "confuse": "kafakarıştırmak", "guards": "korumalar", "attacked": "saldırdılar", "building": "bina", "rescued": "kurtardılar", "minutes": "dakikalar", "soldier": "asker", "fight": "çatışma", "shocked": "şok etti", "protect": "korumak", "citizens": "vatandaşlar", "anywhere": "herhangi bir yer" },
    questions: [ {q:"Was Operation Entebbe a successful rescue mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hijackers release all the passengers immediately?", a_en:"No", a_tr:"Hayır"}, {q:"Did they threaten to kill the hostages?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Israel fly four giant transport planes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use a black Mercedes to confuse the guards?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rescue take 5 hours?", a_en:"No", a_tr:"Hayır"}, {q:"Did the mission show Israel could protect its citizens?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_Finale.mp3"] = [{
    text: "Operation Finale was a secret mission to bring a major war criminal to justice. Adolf Eichmann was one of the men who planned the Holocaust during World War II. After the war, he escaped to Argentina and lived under a fake name, Ricardo Klement. He thought he was safe and lived a quiet life with his family. However, Mossad agents tracked him down. In 1960, a team of agents flew to Argentina secretly. They waited for him near his house and kidnapped him as he was walking home from work. They kept him in a secret 'safe house' for several days to make sure it was really him. Then, they drugged him and dressed him in an airline uniform. They told the airport guards that he was a sick flight attendant. They managed to fly him to Israel on a private plane. Eichmann was put on trial in front of the whole world for his terrible crimes. He was found guilty and executed. This mission showed that war criminals could hide nowhere truly from justice.",
    dict: { "mission": "görev", "bring": "getirmek", "major": "büyük/önemli", "criminal": "suçlu", "justice": "adalet", "planned": "planladı", "Holocaust": "Soykırım", "escaped": "kaçtı", "fake": "sahte", "thought": "düşündü", "safe": "güvenli", "quiet": "sessiz", "tracked down": "izini buldu", "team": "ekip", "flew": "uçtu", "secretly": "gizlice", "waited": "bekledi", "near": "yakınında", "kidnapped": "kaçırdı", "walking": "yürürken", "kept": "tuttu", "several": "birkaç", "days": "günler", "make sure": "emin olmak", "really": "gerçekten", "drugged": "ilaç verdi", "dressed": "giydirdi", "uniform": "üniforma", "guards": "korumalar", "sick": "hasta", "flight attendant": "kabin memuru", "managed": "başardı", "private": "özel", "trial": "duruşma", "front": "önünde", "whole": "bütün", "terrible": "korkunç", "crimes": "suçlar", "found guilty": "suçlu bulundu", "executed": "idam edildi", "hide": "saklanmak", "nowhere": "hiçbir yer" },
    questions: [ {q:"Was Adolf Eichmann a major war criminal?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he escape to Argentina?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Mossad agents kidnap him near his house?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they dress him in a police uniform?", a_en:"No", a_tr:"Hayır"}, {q:"Did they tell the guards he was a sick flight attendant?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he put on trial for his crimes?", a_en:"Yes", a_tr:"Evet"}, {q:"Can war criminals hide safely from justice forever?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["11_Gunnerside.mp3"] = [{
    text: "Operation Gunnerside was a vital mission to stop the Nazis from building an atomic bomb. During World War II, the Germans were using a factory in occupied Norway to produce 'heavy water,' which is needed for nuclear science. The British and the Norwegians knew they had to destroy the factory. A team of six Norwegian saboteurs jumped from a plane into the snowy mountains. They were expert skiers and survived the freezing cold for many days. They climbed down a very steep cliff, crossed a frozen river, and climbed up to the factory. They secretly entered the building and placed explosives on the heavy water machines. The explosion destroyed the factory’s production. The men then skied hundreds of kilometers across the mountains to escape into neutral Sweden. They fired no shots during the mission. This spectacular operation was a huge success and it delayed the German nuclear program, helping to win the war. It is remembered as one of the best examples of sabotage in history.",
    dict: { "vital": "hayati", "mission": "görev", "stop": "durdurmak", "building": "inşa etme/yapma", "atomic": "atomik", "bomb": "bomba", "factory": "fabrika", "occupied": "işgal edilmiş", "produce": "üretmek", "heavy": "ağır", "nuclear": "nükleer", "science": "bilim", "destroy": "yok etmek", "saboteurs": "sabotajcılar", "jumped": "atladılar", "snowy": "karlı", "expert": "uzman", "skiers": "kayakçılar", "survived": "hayatta kaldılar", "freezing": "dondurucu", "climbed down": "aşağı tırmandılar", "steep": "dik", "cliff": "uçurum", "crossed": "geçtiler", "frozen": "donmuş", "river": "nehir", "entered": "girdiler", "placed": "yerleştirdiler", "explosives": "patlayıcılar", "machines": "makineler", "explosion": "patlama", "production": "üretim", "escape": "kaçmak", "neutral": "tarafsız", "fired": "ateşlediler", "shots": "atışlar/mermiler", "spectacular": "muhteşem", "success": "başarı", "delayed": "geciktirdi", "program": "program", "win": "kazanmak", "sabotage": "sabotaj" },
    questions: [ {q:"Was the mission to stop the Nazis from building an atomic bomb?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the Germans producing 'heavy water' in Norway?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the saboteurs jump from a plane into snowy mountains?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they place explosives on the machines?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they fire no shots during the mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the men escape to France?", a_en:"No", a_tr:"Hayır"}, {q:"Did the operation delay the German nuclear program?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_Isotope.mp3"] = [{
    text: "Operation Isotope was a daring rescue of a hijacked airplane. In May 1972, four terrorists from the Black September group hijacked a Sabena flight traveling from Belgium to Israel. They forced the pilot to land at Lod Airport near Tel Aviv. They took 100 people hostage and demanded the release of 317 prisoners. They threatened to blow up the plane with everyone inside. The Israeli government pretended to negotiate with the hijackers. They told the terrorists that the plane needed repairs before it could fly again. A group of sixteen commandos, including future leaders Ehud Barak and Benjamin Netanyahu, dressed up as airplane mechanics in white overalls. They walked toward the plane carrying their tools, but their weapons were hidden under their clothes. They suddenly stormed the plane through the doors. In less than two minutes, they killed the two male terrorists and captured the two female terrorists. All the passengers were saved, although one woman was accidentally killed in the crossfire. This fast and clever operation was a major success for Israel’s special forces.",
    dict: { "daring": "cesur", "rescue": "kurtarma", "hijacked": "kaçırılmış", "airplane": "uçak", "terrorists": "teröristler", "traveling": "seyahat eden", "forced": "zorladılar", "pilot": "pilot", "hostage": "rehine", "demanded": "talep ettiler", "release": "serbest bırakma", "prisoners": "mahkumlar", "threatened": "tehdit ettiler", "blow up": "havaya uçurmak", "inside": "içinde", "government": "hükümet", "pretended": "numara yaptı", "negotiate": "müzakere etmek", "repairs": "tamirler", "fly": "uçmak", "commandos": "komandolar", "future": "gelecek", "leaders": "liderler", "dressed up": "giyindiler", "mechanics": "tamirciler", "white": "beyaz", "overalls": "tulumlar", "walked": "yürüdüler", "toward": "doğru", "carrying": "taşıyan", "tools": "aletler", "weapons": "silahlar", "hidden": "gizli", "clothes": "kıyafetler", "stormed": "baskın yaptılar", "doors": "kapılar", "less than": "daha az", "minutes": "dakikalar", "killed": "öldürdüler", "male": "erkek", "captured": "yakaladılar", "female": "kadın", "saved": "kurtarıldı", "accidentally": "kazara", "crossfire": "çapraz ateş", "clever": "zeki/akıllı", "success": "başarı" },
    questions: [ {q:"Did terrorists hijack an airplane traveling to Israel?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they demand the release of 317 prisoners?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Israeli government pretend to negotiate?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the commandos dress up as airplane mechanics?", a_en:"Yes", a_tr:"Evet"}, {q:"Were their weapons hidden under their clothes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rescue take three hours?", a_en:"No", a_tr:"Hayır"}, {q:"Was the operation a major success?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_IvyBells.mp3"] = [{
    text: "Operation Ivy Bells was an incredible underwater spy mission during the Cold War. The United States Navy discovered that the Soviet Union had a secret military cable on the bottom of the Sea of Okhotsk. This cable carried private messages between Soviet naval bases. The US wanted to listen to these messages. Special divers used a submarine to go very deep into the freezing ocean. They found the cable and placed a large listening device on top of it. This device cut no cables, so the Soviets knew nothing about it. Every month, a submarine would return to collect the tapes with the recorded messages. This gave the US very important secrets about the Soviet military for ten years. However, in 1981, a man working for the US intelligence agency sold the secret to the Soviets for money. The Soviets went to the bottom of the ocean and took the device. The US only realized the mission was over when they saw the empty spot on the sea floor.",
    dict: { "incredible": "inanılmaz", "underwater": "sualtı", "spy": "casus", "mission": "görev", "Cold War": "Soğuk Savaş", "Navy": "Donanma", "discovered": "keşfetti", "secret": "gizli", "military": "askeri", "cable": "kablo", "bottom": "alt/dip", "Sea": "Deniz", "carried": "taşıdı", "private": "özel", "messages": "mesajlar", "naval": "donanma", "bases": "üsler", "listen": "dinlemek", "Special": "Özel", "divers": "dalgıçlar", "used": "kullandı", "submarine": "denizaltı", "deep": "derin", "freezing": "dondurucu", "ocean": "okyanus", "placed": "yerleştirdiler", "listening": "dinleme", "device": "cihaz", "top": "üst", "cut": "kesti", "cables": "kablolar", "knew": "biliyordu", "nothing": "hiçbir şey", "Every": "her", "month": "ay", "return": "geri dönmek", "collect": "toplamak", "tapes": "kasetler", "recorded": "kaydedilmiş", "gave": "verdi", "important": "önemli", "secrets": "sırlar", "working": "çalışan", "agency": "ajans/teşkilat", "sold": "sattı", "money": "para", "took": "aldı", "realized": "fark etti", "empty": "boş", "spot": "nokta/yer", "floor": "zemin" },
    questions: [ {q:"Was Operation Ivy Bells an underwater spy mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the US Navy find a Soviet military cable?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the device cut no cables?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Soviets know nothing about the device at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the submarine return every month to collect tapes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the US keep the secret safely forever?", a_en:"No", a_tr:"Hayır"}, {q:"Did someone sell the secret to the Soviets?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_Jaque.mp3"] = [{
    text: "Operation Jaque was a brilliant and peaceful rescue mission in Colombia. For many years, a rebel group called the FARC held many people as hostages in the thick jungle. This included the famous politician Ingrid Betancourt and three American workers. The Colombian military spent a long time planning a trick to save them. They created a fake humanitarian group. They used helicopters and painted them white to look like they belonged to an international aid organization. The soldiers dressed in civilian clothes and acted like doctors and reporters. They met with the rebels and told them they needed to move the hostages to a different camp. The rebels believed the trick and let the hostages get onto the helicopter. Once the helicopter was high in the air, the soldiers told the hostages, 'We are the national army. You are free.' The rebels on the ground had no idea what happened until it was too late. Nobody was shot during this perfect and clever mission. It was a massive victory for Colombia.",
    dict: { "brilliant": "parlak/muhteşem", "peaceful": "barışçıl", "rescue": "kurtarma", "mission": "görev", "rebel": "isyancı", "group": "grup", "held": "tuttu", "hostages": "rehineler", "thick": "kalın/sık", "jungle": "orman", "included": "içeriyordu", "politician": "politikacı", "workers": "işçiler", "military": "ordu", "spent": "harcadı", "planning": "planlama", "trick": "hile/kandırmaca", "fake": "sahte", "humanitarian": "insani", "helicopters": "helikopterler", "painted": "boyadılar", "white": "beyaz", "belonged": "ait olmak", "international": "uluslararası", "aid": "yardım", "organization": "organizasyon", "soldiers": "askerler", "civilian": "sivil", "clothes": "kıyafetler", "acted": "davrandılar", "doctors": "doktorlar", "reporters": "muhabirler", "met": "buluştular", "move": "taşımak", "different": "farklı", "camp": "kamp", "believed": "inandılar", "get onto": "binmek", "high": "yüksek", "air": "hava", "national": "ulusal", "free": "özgür", "ground": "yer/zemin", "idea": "fikir", "happened": "oldu", "Nobody": "hiç kimse", "shot": "vuruldu", "perfect": "mükemmel", "clever": "zeki/akıllı", "massive": "muazzam", "victory": "zafer" },
    questions: [ {q:"Was Operation Jaque a peaceful rescue mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rebels hold people hostage in the jungle?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the military create a fake humanitarian group?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the soldiers dress like rebels?", a_en:"No", a_tr:"Hayır"}, {q:"Did the rebels believe the trick?", a_en:"Yes", a_tr:"Evet"}, {q:"Was nobody shot during the mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rebels have no idea what happened?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_NeptuneSpear.mp3"] = [{
    text: "Operation Neptune Spear was the top-secret mission to find and kill Osama bin Laden. For ten years after the 9/11 attacks, the United States searched for the leader of Al-Qaeda. Finally, intelligence found that he was hiding in a large, private house in Abbottabad, Pakistan. President Barack Obama ordered a secret night raid. A team of US Navy SEALs flew from Afghanistan in special helicopters that were designed to be quiet and invisible to radar. They landed inside the walls of the house and began a fast gunfight with the guards. They found bin Laden on the third floor and killed him. They also took many computers and documents to learn more about his group. The entire mission lasted only about 40 minutes. One helicopter crashed during the landing, but no Americans were killed. They blew up the broken helicopter and flew away before the Pakistani military could arrive. This operation was one of the most important events in the history of the war on terror.",
    dict: { "top-secret": "çok gizli", "mission": "görev", "find": "bulmak", "kill": "öldürmek", "attacks": "saldırılar", "searched": "aradılar", "leader": "lider", "intelligence": "istihbarat", "found": "buldu", "hiding": "saklanıyor", "large": "büyük", "private": "özel", "house": "ev", "ordered": "emretti", "night": "gece", "raid": "baskın", "team": "ekip/takım", "flew": "uçtular", "special": "özel", "helicopters": "helikopterler", "designed": "tasarlanmış", "quiet": "sessiz", "invisible": "görünmez", "radar": "radar", "landed": "indiler", "inside": "içine", "walls": "duvarlar", "began": "başladılar", "fast": "hızlı", "gunfight": "silahlı çatışma", "guards": "korumalar", "floor": "kat", "computers": "bilgisayarlar", "documents": "belgeler", "learn": "öğrenmek", "entire": "bütün/tüm", "lasted": "sürdü", "minutes": "dakikalar", "crashed": "çarptı/düştü", "landing": "iniş", "killed": "öldürüldü", "blew up": "havaya uçurdular", "broken": "kırık/bozuk", "arrive": "varmak/ulaşmak", "important": "önemli", "events": "olaylar", "history": "tarih", "war": "savaş", "terror": "terör" },
    questions: [ {q:"Was Operation Neptune Spear a top-secret mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the US search for bin Laden for ten years?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he hide in a large house in Pakistan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Navy SEALs use special quiet helicopters?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the mission last for five hours?", a_en:"No", a_tr:"Hayır"}, {q:"Were no Americans killed during the mission?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they take computers and documents from the house?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_Nimrod.mp3"] = [{
    text: "Operation Nimrod was a spectacular hostage rescue that happened live on television. in 1980, six armed men took over the Iranian Embassy in London. They took 26 people hostage and demanded that Iran release prisoners. The siege lasted for six days while the police tried to talk to the gunmen. On the sixth day, the gunmen killed one of the hostages and threw his body out of the front door. The British government decided to send the SAS, a group of elite soldiers. Millions of people watched on the news as the black-clothed soldiers climbed down ropes from the roof and used explosives to enter the windows. The soldiers moved very fast through the smoke and fire. They killed five of the six terrorists and saved almost all the hostages. Only one hostage was killed by the gunmen during the attack. This mission made the SAS very famous around the world and showed that Britain was very strong against terrorism.",
    dict: { "spectacular": "muhteşem", "hostage": "rehine", "rescue": "kurtarma", "happened": "oldu", "live": "canlı", "television": "televizyon", "armed": "silahlı", "men": "adamlar", "took over": "ele geçirdiler", "Embassy": "Büyükelçilik", "demanded": "talep ettiler", "release": "serbest bırakma", "prisoners": "mahkumlar", "siege": "kuşatma", "lasted": "sürdü", "days": "günler", "police": "polis", "tried": "denediler", "talk": "konuşmak", "gunmen": "silahlı adamlar", "killed": "öldürdüler", "threw": "attılar", "body": "beden/ceset", "front": "ön", "door": "kapı", "government": "hükümet", "decided": "karar verdi", "send": "göndermek", "elite": "seçkin", "soldiers": "askerler", "watched": "izlediler", "news": "haberler", "black-clothed": "siyah giyimli", "climbed down": "aşağı tırmandılar", "ropes": "ipler", "roof": "çatı", "explosives": "patlayıcılar", "enter": "girmek", "windows": "pencereler", "moved": "hareket ettiler", "fast": "hızlı", "through": "içinden/arasından", "smoke": "duman", "fire": "ateş", "saved": "kurtardılar", "almost": "neredeyse", "attack": "saldırı", "famous": "ünlü", "world": "dünya", "strong": "güçlü", "terrorism": "terörizm" },
    questions: [ {q:"Did the rescue happen live on television?", a_en:"Yes", a_tr:"Evet"}, {q:"Did armed men take over the Iranian Embassy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the siege last for six days?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the gunmen throw a body out the door?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the SAS soldiers climb up from the ground?", a_en:"No", a_tr:"Hayır"}, {q:"Did they use explosives to enter the windows?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the mission make the SAS very famous?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_Oak.mp3"] = [{
    text: "Operation Oak was a daring and spectacular rescue of the Italian leader, Benito Mussolini. In 1943, Mussolini was arrested by his own government and hidden in a hotel on top of a high mountain called Gran Sasso. The only way to get to the hotel was by a cable car, which was guarded by soldiers. Adolf Hitler wanted to save his friend Mussolini. He sent a group of paratroopers and a special agent named Otto Skorzeny. They used ten gliders to land silently on the small, rocky ground near the hotel. The Italian guards were so surprised that they fired no shots. The Germans entered the hotel and took Mussolini away. Then, a small, light airplane landed on the dangerous mountain slope. Mussolini and Skorzeny got into the plane and flew away to safety in Germany. This rescue was a huge propaganda success for the Nazis and it showed the incredible skill of their special forces. It is remembered as one of the most famous raids of World War II.",
    dict: { "daring": "cesur", "spectacular": "muhteşem", "rescue": "kurtarma", "leader": "lider", "arrested": "tutuklandı", "government": "hükümet", "hidden": "saklandı", "hotel": "otel", "mountain": "dağ", "called": "adlandırılan", "cable car": "teleferik", "guarded": "korunan", "soldiers": "askerler", "save": "kurtarmak", "friend": "arkadaş", "sent": "gönderdi", "group": "grup", "paratroopers": "paraşütçüler", "special": "özel", "agent": "ajan", "used": "kullandı", "gliders": "planörler", "land": "inmek", "silently": "sessizce", "rocky": "kayalık", "ground": "zemin", "near": "yakınında", "guards": "korumalar", "surprised": "şaşırmış", "fired": "ateşlediler", "shots": "atışlar", "entered": "girdiler", "took away": "alıp götürdüler", "light": "hafif", "airplane": "uçak", "dangerous": "tehlikeli", "slope": "yamaç", "got into": "bindiler", "flew": "uçtular", "safety": "güvenlik", "propaganda": "propaganda", "success": "başarı", "showed": "gösterdi", "incredible": "inanılmaz", "skill": "yetenek/beceri", "forces": "kuvvetler", "remembered": "hatırlanır", "raids": "baskınlar" },
    questions: [ {q:"Was Mussolini hidden in a hotel on a high mountain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Hitler want to save his friend Mussolini?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use gliders to land silently?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Italian guards fire no shots?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use a big helicopter to fly away?", a_en:"No", a_tr:"Hayır"}, {q:"Did a small airplane land on the dangerous slope?", a_en:"Yes", a_tr:"Evet"}, {q:"Was this rescue a huge propaganda success for the Nazis?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_PuebloIncident.mp3"] = [{
    text: "The Pueblo Incident was a spectacular and scary event during the Cold War. The USS Pueblo was a US Navy spy ship that was sailing near North Korea to listen to their communications. In January 1968, North Korean ships and planes suddenly attacked the ship in international waters. One American sailor was killed and the rest of the 82 crew members were captured. This was a massive shock because it was the first time a US Navy ship was captured in over 150 years. The crew was taken to North Korea and held as prisoners for eleven months. They were treated very badly and were forced to say that they were spies. The United States was very angry and almost went to war with North Korea. Finally, after many months of talking, the US signed a letter to apologize so the crew could be released. The crew returned home, but the North Koreans kept the ship. Today, the USS Pueblo is still in North Korea and is used as a museum to show their victory.",
    dict: { "Incident": "Olay", "spectacular": "muhteşem/çarpıcı", "scary": "korkutucu", "event": "olay", "Navy": "Donanma", "spy": "casus", "ship": "gemi", "sailing": "seyreden", "listen": "dinlemek", "communications": "iletişim/haberleşme", "planes": "uçaklar", "suddenly": "aniden", "attacked": "saldırdılar", "international": "uluslararası", "waters": "sular", "sailor": "denizci", "killed": "öldürüldü", "crew": "mürettebat", "members": "üyeler", "captured": "yakalandı", "massive": "muazzam", "shock": "şok", "first time": "ilk kez", "held": "tutuldu", "prisoners": "mahkumlar", "months": "aylar", "treated": "muamele gördü", "badly": "kötü bir şekilde", "forced": "zorlandı", "say": "söylemek", "spies": "casuslar", "angry": "öfkeli", "almost": "neredeyse", "went to war": "savaşa girdi", "talking": "konuşma", "signed": "imzaladı", "letter": "mektup", "apologize": "özür dilemek", "released": "serbest bırakıldı", "returned": "döndü", "kept": "tuttu/sakladı", "Today": "bugün", "still": "hala", "used": "kullanılır", "museum": "müze", "show": "göstermek", "victory": "zafer" },
    questions: [ {q:"Was the USS Pueblo a spy ship?", a_en:"Yes", a_tr:"Evet"}, {q:"Did North Korea attack the ship in international waters?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the crew held as prisoners for eleven months?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the crew members treated very well?", a_en:"No", a_tr:"Hayır"}, {q:"Did the US sign a letter to apologize?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the US get the ship back?", a_en:"No", a_tr:"Hayır"}, {q:"Is the ship used as a museum today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_RainbowWarrior.mp3"] = [{
    text: "The Rainbow Warrior was a ship owned by Greenpeace, an organization that protests against nuclear testing. In 1985, the ship was in a harbor in Auckland, New Zealand. It was preparing to sail to a small island in the Pacific to protest against French nuclear tests. The French government wanted to stop the ship, so they sent a secret team of agents to New Zealand. The agents pretended to be tourists. At night, they swam under the ship and placed two bombs on its side. The bombs exploded and the ship sank very quickly. Sadly, one photographer on board was killed. The French agents tried to escape, but the New Zealand police caught two of them. This caused a massive international scandal. At first, the French government said they did nothing wrong, but later they had to admit the truth. This event made many people angry at France and it is remembered as a major blunder in the history of secret intelligence operations.",
    dict: { "Warrior": "Savaşçı", "ship": "gemi", "owned by": "sahibi olan", "organization": "organizasyon", "protests": "protesto eder", "nuclear": "nükleer", "testing": "test etme", "harbor": "liman", "preparing": "hazırlanan", "sail": "yelken açmak/denize açılmak", "island": "ada", "stop": "durdurmak", "sent": "gönderdi", "secret": "gizli", "team": "ekip", "agents": "ajanlar", "pretended": "numara yaptılar", "tourists": "turistler", "night": "gece", "swam": "yüzdüler", "placed": "yerleştirdiler", "bombs": "bombalar", "exploded": "patladı", "sank": "battı", "quickly": "hızlıca", "Sadly": "ne yazık ki", "photographer": "fotoğrafçı", "on board": "gemide", "killed": "öldürüldü", "tried": "denediler", "escape": "kaçmak", "police": "polis", "caught": "yakaladı", "caused": "sebep oldu", "massive": "muazzam", "international": "uluslararası", "scandal": "skandal", "nothing": "hiçbir şey", "wrong": "yanlış", "admit": "itiraf etmek", "truth": "gerçek", "event": "olay", "angry": "öfkeli", "remembered": "hatırlanır", "major": "büyük", "blunder": "hata/gaf", "history": "tarih", "intelligence": "istihbarat", "operations": "operasyonlar" },
    questions: [ {q:"Was the Rainbow Warrior owned by Greenpeace?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the ship want to protest against French nuclear tests?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the French agents pretend to be tourists?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the agents swim under the ship and place bombs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the French government say they did nothing wrong at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the agents escape without getting caught?", a_en:"No", a_tr:"Hayır"}, {q:"Is it remembered as a major blunder?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_Valkyrie.mp3"] = [{
    text: "Operation Valkyrie was a famous and tragic attempt by German officers to kill Adolf Hitler. By 1944, many German leaders realized that Hitler was leading the country to destruction and they wanted to end World War II. A brave officer named Claus von Stauffenberg led the plan. He took a briefcase with a bomb inside to a secret meeting with Hitler in a wooden building. He placed the briefcase under the table near Hitler and then left the room to make a phone call. The bomb exploded and destroyed the room. Stauffenberg believed Hitler was dead and flew to Berlin to start a new government. However, Hitler survived because a heavy table leg protected him from the blast. The plan failed because the officers in Berlin were confused and acted with no speed. Hitler’s soldiers soon arrested Stauffenberg and the other leaders. They were all executed that same night. This was the most serious attempt to kill Hitler and it showed that even within the Nazi army, there were people who wanted peace.",
    dict: { "famous": "ünlü", "tragic": "trajik", "attempt": "girişim", "officers": "subaylar", "kill": "öldürmek", "realized": "fark ettiler", "leading": "yöneten/sürükleyen", "destruction": "yıkım", "wanted": "istediler", "end": "bitirmek", "brave": "cesur", "named": "adında", "led": "yönetti/liderlik etti", "plan": "plan", "took": "aldı/götürdü", "briefcase": "evrak çantası", "bomb": "bomba", "inside": "içinde", "meeting": "toplantı", "wooden": "ahşap", "building": "bina", "placed": "yerleştirdi", "table": "masa", "near": "yakın", "left": "ayrıldı", "phone call": "telefon görüşmesi", "exploded": "patladı", "destroyed": "yok etti", "room": "oda", "believed": "inandı", "dead": "ölü", "flew": "uçtu", "start": "başlatmak", "government": "hükümet", "survived": "hayatta kaldı", "heavy": "ağır", "leg": "bacak/ayak", "protected": "korudu", "blast": "patlama", "failed": "başarısız oldu", "confused": "kafası karışmış", "acted": "hareket ettiler", "speed": "hız", "soldiers": "askerler", "soon": "kısa süre sonra", "arrested": "tutukladılar", "executed": "idam edildiler", "serious": "ciddi", "showed": "gösterdi", "within": "içinde", "army": "ordu", "peace": "barış" },
    questions: [ {q:"Did German officers want to end World War II?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Stauffenberg place a bomb under the table?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Hitler survive the blast?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the officers in Berlin act with no speed?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Stauffenberg manage to escape?", a_en:"No", a_tr:"Hayır"}, {q:"Were the leaders executed that same night?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the attempt show that some people in the army wanted peace?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_WrathOfGod.mp3"] = [{
    text: "Operation Wrath of God was a long and secret mission for revenge. In 1972, a terrorist group killed eleven Israeli athletes at the Olympic Games in Munich. Israel was devastated and angry. Prime Minister Golda Meir ordered a secret team of Mossad agents to find and kill everyone who was involved in the massacre. For more than fifteen years, the team traveled across Europe and the Middle East in secret. They used many different ways to kill the targets, including bombs in telephones and beds. One time, they made a mistake and killed an innocent man in Norway because they thought he was a terrorist. This was a major international problem. However, the mission continued for many more years. Some people say this operation was necessary for justice, while others say it was a violent cycle of revenge. The mission was so famous that it was later made into a movie called Munich. It remains one of the most controversial secret operations in history.",
    dict: { "Wrath": "Gazap/Öfke", "God": "Tanrı", "secret": "gizli", "mission": "görev", "revenge": "intikam", "terrorist": "terörist", "group": "grup", "killed": "öldürdü", "athletes": "sporcular", "Olympic Games": "Olimpiyat Oyunları", "devastated": "yıkılmış/mahvolmuş", "angry": "öfkeli", "Prime Minister": "Başbakan", "ordered": "emretti", "team": "ekip", "agents": "ajanlar", "find": "bulmak", "everyone": "herkes", "involved": "karışmış/dahil olan", "massacre": "katliam", "traveled": "seyahat ettiler", "across": "boyunca", "Europe": "Avrupa", "Middle East": "Orta Doğu", "different": "farklı", "ways": "yollar/yöntemler", "targets": "hedefler", "including": "dahil olmak üzere", "bombs": "bombalar", "telephones": "telefonlar", "beds": "yataklar", "mistake": "hata", "innocent": "masum", "thought": "düşündüler", "major": "büyük", "international": "uluslararası", "problem": "sorun", "continued": "devam etti", "necessary": "gerekli", "justice": "adalet", "while": "iken (zıtlık)", "violent": "şiddetli", "cycle": "döngü", "famous": "ünlü", "movie": "film", "called": "adlandırılan", "remains": "kalır/olmaya devam eder", "controversial": "tartışmalı", "history": "tarih" },
    questions: [ {q:"Was Operation Wrath of God a mission for revenge?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a terrorist group kill Israeli athletes in Munich?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Mossad team travel in secret for more than fifteen years?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use bombs in telephones and beds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they never make a mistake?", a_en:"No", a_tr:"Hayır"}, {q:"Did they kill an innocent man in Norway by mistake?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the operation still considered controversial?", a_en:"Yes", a_tr:"Evet"} ]
}];
